### ISSUE TITLE
[feat]: Increase DB Cache Limit Based on Available Memory

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/bitcoind-wrapper#101]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Currently the limit is 1024M, which makes sense on the Pi, but it will be nice to be able to crank that up on the Pro and other high-powered v0.3.3+ devices

Need concept ACK on whether to universally raise limit (simple) or somehow create limit as a percentage of total RAM (less simple)

### Describe the Use Case

Faster IBD

**Comment by BitcoinMechanic** [comment]
Can the service just ascertain what device it's on and allow a much higher limit if it detects that it's running on a pro?

I agree that limiting the Pro to 1024mb dbcache is a mistake. ~25gb is doable for the Pro and that is currently enough to never have to write to disk for the entire IBD. We'd definitely want to allow this for benchmarking.

**Comment by kn0wmad** [comment]
Probably more general purpose to detect total RAM, @dr-bonez not sure how big this lift is?

**Comment by kn0wmad** [comment]
Requires writing a smarter `getConfig` - suggesting P1 for v24 at latest, more ideally eOS v033

**Comment by chrisguida** [comment]
Duplicate of https://github.com/Start9Labs/bitcoind-wrapper/issues/39

**Comment by kn0wmad** [comment]
Closing as dupe
