### ISSUE TITLE
Test Service Backups

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/bitcoind-wrapper#13]
- [x] bitcoind
- [x] c-lightning
- [x] ride-the-lightning
- [x] thunderhub
- [x] mastodon
- [x] synapse

**Comment by ProofOfKeags** [comment]
Is there a reason all these tasks are cut against the bitcoind-wrapper repo?

**Comment by chrisguida** [comment]
@ProofOfKeags because i believe embassy-os wasn't an option when i was creating the ticket. Closing

**Comment by chrisguida** [comment]
I have added embassy-os as a linked repo on the Service Issues project board, so now we can just use that if something applies to every service
