### ISSUE TITLE
Update Bitcoind to v22.0

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/bitcoind-wrapper#47]
- [x] Bitcoin Core released [v22.0](https://github.com/bitcoin/bitcoin/releases/tag/v22.0) last September. Note this is NOT '0.22' but '22.0' because Bitcoin Core changed their versioning scheme and we should synchronize with that.
- [x] Look at any new features in the release notes and ingest relevant config options into the new config. The sample config can be found [here](https://github.com/bitcoin/bitcoin/blob/master/share/examples/bitcoin.conf)
- [x] #53

Optional:
- [ ] Start9Labs/operations#23

We cannot publish this eagerly, so make sure that when this is done it doesn't make it to production until the dependent services have their commensurate updates. 

Edit: We can push this and btc-rpc-proxy out without affecting anything. Btcpay and LND need to have their dependency requirements updated as well for this to work.

**Comment by chrisguida** [comment]
candidates for new conf options: `blockfilterindex`, `peerblockfilters`, `testnet`
