### ISSUE TITLE
Dependencies - appmgr - link is 404

### ISSUE THREAD

**Issue by kamadom** [Start9Labs/bitcoind-wrapper#62]
Dependencies include "appmgr" but the link https://github.com/Start9Labs/embassy-os/tree/master/appmgr leads to a deadend.  

Searching GitHub https://github.com/search?q=appmgr reveals 26 repository results.  

Which is the intended link for "appmgr"?  Is this the correct link:  https://github.com/appmgr/appmgr

Many thanks for responding!

**Comment by chrisguida** [comment]
The readme is out of date. Updating this now, actually.

**Comment by chrisguida** [comment]
Fixed in 37e6d8be9e6ce938f5defdc5d3ece4cc88e6fb13
