### ISSUE TITLE
[feat] Add Bloom Filters [BIP37] to Config

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/bitcoind-wrapper#67]
This allows Bisq integration.

Include warning that general use is recommended against.

**Comment by kn0wmad** [comment]
Closing as this is in latest Master

**Comment by chrisguida** [comment]
Please update with a PR or a commit hash where the fix occurred.

**Comment by kn0wmad** [comment]
This is mentioned immediately above my comment, #72
