### ISSUE TITLE
[bug]: reindex blockchain action says we prune by default - we don't

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/bitcoind-wrapper#84]
![image](https://user-images.githubusercontent.com/45926711/180084243-abb8ba5b-187b-4cb1-9cfd-159ec9068b4f.png)

**Comment by BitcoinMechanic** [comment]
Will be closed by https://github.com/Start9Labs/bitcoind-wrapper/pull/92

**Comment by chrisguida** [comment]
Actually this was already fixed in #91
