### ISSUE TITLE
[bug]: Reindex Action Copy Fix

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/bitcoind-wrapper#90]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Phone/tablet

### Device OS

MacOS

### Device OS Version

n/a

### Browser

Firefox

### Browser Version

n/a

### Current Behavior

![image](https://user-images.githubusercontent.com/39687477/184977575-e9aa29c8-b685-48ef-a3f7-e83f63206b4f.png)

Bitcoin nodes are no longer pruned by default

### Expected Behavior

copy change

### Steps to Reproduce

Actions page -> Reindex

**Comment by chrisguida** [comment]
What wording would you would like to see?

**Comment by kn0wmad** [comment]
Just need to remove wording on bitcoin being pruned by default, since it's not, but yes I'll PR

**Comment by chrisguida** [comment]
Fixed by #91
